### ISSUE TITLE
Decrease size of X3DOM github project

### ISSUE THREAD

**Issue by mlimper** [x3dom/x3dom#303] opened 2014-02-19 17:09 UTC
The X3DOM project has now grown to almost 1GB of data.
Much stuff actually belongs in a separate example repository (such as examples.x3dom.org), simply on any other web server (such as the publications), or it is completely outdated anyway. (Luckily, nothing gets lost with Git, so there is also no need for an "archive" folder or things like that ;- )

The "test/functional" folder is more than half a GB large, so this is definitely the most important folder to clean up (-> move stuff to showcase/examples page and to the regression suite, clean up everything else)

**Comment by Hornwitser** [comment] 2016-04-13 01:38
As of April 2016 the repository has just passed 1 GB in size for a full clone.  Checked out, there are about 600 MB of files in the tree, about half of which is taken up by 3D textures. The remaining 400 MB of data in the repository are files that have since been removed from the tree, but are kept in the history.

That last point is important.  Even if we were to delete 90% of the data from the tree, the files removed will still be in the repository taking up space.  In order to actually clear up data, the **repository history must be rewritten**.

This sucks, as when you do that, everyone downstream that has a local copy of this repository is forced to fix their history manually (see [this](https://git-scm.com/docs/git-rebase#_recovering_from_upstream_rebase) for a description of the process).  This includes all forks done on GitHub. But it's the only way you can trim down the size of the repository and I believe it would be more than worth doing.  This is also a good opportunity to fix #633, since that issues also requires rewriting the history to be fixed.

Before we can do any of this however, a few things needs to be sorted out.  Primarily determining what belongs into this repository, and what does not belong into this repository.  The following is my opinion on what should and should not be in the repository.

**What I think belong in the repository**
- X3DOM code, obviously.  This means any code that is maintained here and used to assemble the released product.
- API documentation.  The only part of the public documentation that I feel is sensible to put into the actual development repository, as it's relatively close to the code.
- Internal documentation.  That is, guidelines for code, structure of the code, instructions on building, requirements, etc.
- Automated test


**What I think *does not* belong in the repository**
- Binaries, generated code, and code maintained elsewhere.  This is a big no-no.  It bloats the repository with code you cannot touch, have to manually make sure is up to date, and fills commits with useless junk that has mostly nothing to do with X3DOM development at all.
- 3D textures. This simply is not the place for collecting 3d scans of interesting stuff. Yes, having a 3D texture for testing is useful for testing, but it takes up *waaay* too much space.  The incisix 3d scan of a human skull certainly looks cool, it also takes up 60 MB of space.  You can fit all of the source code for X3DOM and its history in that amount! For testing 3d textures, some fractal generation code could server the same purpose at 1/1000th of the space.
- Documentation that is not directly related to the API.  While it may seem alright to have the docs right next to the code, the hurdles it make is not justified by them.  A person who writes documentation is not necessarily a coder, and so telling them to clone a repository (a 1 GB one at that!), make their changes, commit them, and then open a pull request to have them merged might to us seem perfectly reasonable, could be incomprehensible gibberish to them.  Obviously some kind of system needs to be used to keep track of changes, but I don't think the development repository is the place for this.  Maybe a dedicated repository for documentation?  Or even a wiki.
- Documents that are not directly related to X3DOM development. For example the stuff currently in doc/misc/slides, while undoubtedly useful to have, doesn't really have much to do with developing X3DOM.  These should be moved to some other place.
- Examples. This basically boils down to the fact that most of the bloat in the repository come from textures and model files bundled with examples.  I also don't see any clear lines for what sort of examples are suitable for inclusion and what sorts are not.
- Tutorials.  For the same reasons as for documentation.
- Textures of any kind really, they just take up space.


**Finally, here's a little graphical illustration**
Maybe not so useful, but I thought it would be nice to see just how much stuff there is compared to the src/ folder.  Blue is png files, purple is jpg files, red is jar files, green is html files, yellow is pdf files, and light blue is dll files.
![visual](https://cloud.githubusercontent.com/assets/14362102/14480171/94284bf2-0126-11e6-96fa-5f1a1c71ad6f.png)

**Comment by mlimper** [comment] 2016-04-13 07:08
Thanks for the nice wrap-up!

We also agreed earlier that the history must be rewritten, there was just no time to do it (obviously requires some time as, like you pointed out, you can break a lot of stuff during that step).

Splitting the docs into two or more completely separated repos (API vs. the rest) is one option, but I'm not sure if it's the best way (makes the generation a bit more complicated / error-prone).
Regarding Tests and Examples, we should definitely do a huge cleanup. I agree with yjung that there must be a simple way to test X3DOM code, without having to build it. For this purpose, we should outline how developers can easily test during development (using gitignore and some way of including the X3DOM sources directly, as for the test/functional files). This information should then be part of the X3DOM tutorials, showing first steps for new developers.

Given the amount of time and all the problems that might arise, I am just thinking how it would be if we would just "restart" with a clean, second repo for x3dom 2.0 and leave the old one as-is... :-D
My experience is that people really just mostly move forward with X3DOM. I don't know anyone who maintains a 1.6 build or something like that.

**Comment by Hornwitser** [comment] 2016-04-13 10:03
I would rather not go for the nuclear option of starting over with a new repository, no matter how bad this is.  As such I've been experimenting with rewriting the history of this repository, and the tools available for this are somewhat crude when it comes to rewriting the 1800 commits between the bogus history merge and the tip of the master branch.  It's mostly a combination of `git cherry-pick`, `git rebase` and a lot `git log`.  The biggest problem is that non conflicting changes in merge commits are lost.  Which will make the history slightly buggy, but it *is* doable.  I will upload a repository with the 1600 commit bogus history rebased out, it will still be 1 GB in size, so nothing saved there, but at least that's one less thing to think about. 

Another thing, I am noticing that the commit history is rather lackluster in the quality of the descriptions.  Most commits have a one line message that barely can be described as a summary of the changes made.  For example, where as I would happily write a [3 paragraph description](https://github.com/Hornwitser/YetiBridge/commit/189758f7ed39d76567298a6a89f2799cd66bd7c8) of a bug fix I made in my code, I see commits who's only descriptions are variants of "fixed a bug" all over the place here.  Which seems to be a bit contrary to the the doc/misc/guide/internals/conventions.rst document. Also contrary to that code guide is the usage of tabs for indent mixed in pretty much everywhere.

Finally I'm not too familiar with how the documentation is generated or how the general flow of development is done, so I'm going to take a closer look at that.  I'm still miles away from looking at the actual issues I came here to fix; the awful controls and behavior of zoom, pan, and rotate in the examine mode :confused:.

**Comment by mlimper** [comment] 2016-04-13 10:19
> Finally I'm not too familiar with how the documentation is generated or how the general flow of development is done, so I'm going to take a closer look at that. I'm still miles away from looking at the actual issues I came here to fix; the awful controls and behavior of zoom, pan, and rotate in the examine mode :confused:.

Oh, sorry for that! That's really far away from this topic.
FWIW, we will have a re-write of parts of the TURNTABLE navigation mode. This is the mode most users really would like to use, instead of EXAMINE. Maybe this will help - but that doesn't belong into this thread, I guess... Here are current tickets associated to TURNTABLE:
https://github.com/x3dom/x3dom/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+turntable
If you really want EXAMINE and think something is wrong there (or with any other navigation mode, in general), please feel free to open a ticket.

**Comment by Hornwitser** [comment] 2016-04-13 11:34
I've uploaded my rebase of the project repository to https://github.com/Hornwitser/x3dom-rewrite, currently there's not changed in it, you can see the commit counter reads 4260 rather than 5950, but that's about it.  The stable branches has not been recreated, and all of the rewritten commits says I'm the committer.

**Comment by mlimper** [comment] 2016-04-13 12:11
> . I will upload a repository with the 1600 commit bogus history rebased out, it will still be 1 GB in size, so nothing saved there, but at least that's one less thing to think about.

That's a very nice offer, thanks for that.


> I would rather not go for the nuclear option of starting over with a new repository, no matter how bad this is. As such I've been experimenting with rewriting the history of this repository, and the tools available for this are somewhat crude [...]

I guess we have to be very careful, as you also mentioned earlier, not to confuse people having their own fork, etc. . From a very practical point of view, I believe that - as bad as it sounds - checking out a > 1GB repo is bad, but obviously still doable for a lot of people, and moving to a fresh git repo will be easy and not error-prone at all. So, before we try hacking the git history again, I would really like to make sure that we know about the effects in advance.

**Comment by Hornwitser** [comment] 2016-04-13 12:19
I'm going to experiment with this to see how GitHub handles forks and pull requests that reference rewritten history.  As well as how it works with the GitHub git client.

**Comment by Hornwitser** [comment] 2016-04-13 16:13
Observations:
- GitHub does not tell you when upstream rewrote their stuff.
- Pull requests created from forks that are not updated will bring in the old history.  These can easily be fended off as they will contain a thousand commits in the pull request description.
- The GitHub desktop GUI is useless for making this change, you need to use the git shell.

In order to fix your fork of the project after the rebase you need to do the following:

1. For every branch you have, find the first commit in their history that was part of the x3dom master branch.

2. If you don't already have upstream as a remote add it with
    `git remote add upstream https://github.com/x3dom/x3dom.git`

3. do `git fetch upstream`

4. for every branch you have developed on do
    1. check out the branch with `git checkout <branch>`

    2. rebase the changes made with
        `git rebase <commit-you-found-in-step-3> --onto upstream/master`

**Comment by Hornwitser** [comment] 2016-04-15 16:02
I've been thinking about this for a bit, and if we remove the stuff that's in the repository that takes up too much space, things will break.  For example test/regression-suite/selenium-server-standalone-*.jar takes up 66 MB of space, but if it's removed the script for running the regression-suite breaks.

So what I thought about was leaving a text file titled something like "REMOVED" in each directory where files have been removed, containing a basic description saying that due to the large size of the x3dom repository, some files has been removed from the repository.  And then a list of the files that has been removed from that directory along with links to where they can be found.  I was thinking of putting up an archive with the removed files as well, just in case the source goes dead.

Now there's one thing I need to know.  What size of the repository are we targeting to reduce it into?  From what I get so far, it should be possible to strip it down to about 50 MB, if every single texture, binary, third party code, and mesh data is out right removed.  Unfortunately, that would also break pretty much everything that isn't x3dom.

**Comment by mlimper** [comment] 2016-04-15 17:13
> From what I get so far, it should be possible to strip it down to about 50 MB, if every single texture, binary, third party code, and mesh data is out right removed. Unfortunately, that would also break pretty much everything that isn't x3dom

Wow, cool - thanks for the analysis!

The part about breaking everything that isn't X3DOM is a bit critical, I guess :-/

That's actually the kind of stuff I had in mind when I proposed to re-start from scratch with the repo and leave the current state as-is. The rebasing is also something I wouldn't want to do, it's just too complex for contributors maintaining forks.

Maybe an option could be to move the current state into some clone / fork and re-start with a cleaned-up version for X3DOM 1.8.

**Comment by Hornwitser** [comment] 2016-04-15 17:28
Well for the contributor maintained forks.  If they want to update, they are going to have to rebase their changes if we start over with a new repo, and the process is going to be more or less exactly the same as if we did a rewrite.

> The part about breaking everything that isn't X3DOM is a bit critical, I guess :-/

But I like breaking things!  On a more serious note though, the breakages would all be due missing files, which if we structure things right could be all automatically downloaded with a simple script.

**Comment by mlimper** [comment] 2016-04-15 17:33
> But I like breaking things! On a more serious note though, the breakages would all be due missing files, which if we structure things right could be all automatically downloaded with a simple script.

Well, I guess the basic problem about the missing files is the conceptual issue you already mentioned: do we want to have regression tests etc. inside the repo? There are pros and cons. If we say yes -> fix them to also work with the cleaned-up repo, whatever that means in the concrete case. If we say no -> move them to a separate repo and make them work first, before we do the rebase / restart / ... .

**Comment by mlimper** [comment] 2016-04-15 17:36
> Well for the contributor maintained forks. If they want to update, they are going to have to rebase their changes if we start over with a new repo, and the process is going to be more or less exactly the same as if we did a rewrite.

The part "find the first commit that is also part of the master branch" is a bit complex, in my personal opinion. It would be great if we could avoid something like that (I mean really avoid, not automate or so).

**Comment by Hornwitser** [comment] 2016-04-24 22:26
I did a little experiment, and removed the whole test/ and example/ directory from the repository, and it shrunk down to 170 MB.

Most of the bloat left then is doc/misc/slides, doc/misc/iX, doc/x3doc/base/tutorials, tools/util/BVHRefiner DataSet Converter/, and some test_*.xhtml files under src/ and src_mobile/.

**Closed** 2017-04-25 08:45 UTC
Labels: consolidation, optimization

**Comment by paulmasson** [comment] 2020-07-05 22:54
In the event someone comes across this closed issue and would like a smaller local repository, Git allows shallow clones without the commit history. Use a command like this:

```
git clone --depth=1 https://github.com/x3dom/x3dom.git
```
