### ISSUE TITLE
maximum call stack size exceeded on 1.8.3

### ISSUE THREAD

**Issue by whunter** [x3dom/x3dom#1302] opened 2023-09-25 21:26 UTC
Hi,
I'll be upfront. I'm really just dipping my toe in the waters of web 3d stuff. I have no idea what I'm doing.

Anyway, the models that our 3d lab has produced are failing to render as of 1.8.3. The x3dom.js script is throwing this error:

```
x3dom.js:7 Uncaught RangeError: Maximum call stack size exceeded
    at Object.nodeChanged (x3dom.js:7:819582)
    at x3dom.NodeNameSpace.setupTree (x3dom.js:7:147526)
    at x3dom.NodeNameSpace.<anonymous> (x3dom.js:7:147451)
    at NodeList.forEach (<anonymous>)
    at x3dom.NodeNameSpace.setupTree (x3dom.js:7:147419)
    at x3dom.NodeNameSpace.<anonymous> (x3dom.js:7:147451)
    at NodeList.forEach (<anonymous>)
    at x3dom.NodeNameSpace.setupTree (x3dom.js:7:147419)
    at Object.loadX3D (x3dom.js:7:700943)
    at o.onreadystatechange (x3dom.js:7:703601)
```
    
You can see version 1.8.2 running one of our models here:
https://x3dom-1-8-2.d234tdmg9icdwk.amplifyapp.com/archive/ch404901
    
And 1.8.3 is here (pointing to the same assets):
https://3d.d234tdmg9icdwk.amplifyapp.com/archive/ch404901
But this one throws the above error.

They're both pointing to this external x3d file:
https://img.cloud.lib.vt.edu/swva/Entomo3D/demo/LowRes_VTEC000004901_X3D.x3d

I'm fully aware that this is probably a problem with my implementation but I wanted to let you all know because it just started happening with the new release. 

And if anyone had any advice on how to fix this (other than just pinning it to 1.8.2) I certainly wouldn't object.

Thanks!

**Comment by andreasplesch** [comment] 2023-09-26 02:06
Thanks for reporting.

Wow, such a beautiful butterfly !

The problem is that the model has more than 65K tex. coord. indices, and hits a limit of the browser javascript engine not accepting that many function parameters. 1.8.3 now attempts to fill in missing indices, ironically to avoid other crashes.

This accidentally had just come up and was fixed in the latest dev. version:

https://github.com/x3dom/x3dom/pull/1296/commits/9598c3f0fbce7a2ba7264c5aa911bbf3c8c39b25

https://andreasplesch.github.io/Library/Viewer/index.html?url=https://img.cloud.lib.vt.edu/swva/Entomo3D/demo/LowRes_VTEC000004901_X3D.x3d

You could build it from source (very easy, see https://github.com/x3dom/x3dom/wiki/Online-Build-Instructions) or get it from https://andreasplesch.github.io/x3dom/dist/x3dom.js (as well as all other builds).

Wondering how large the HiRes version gets.

**Comment by andreasplesch** [comment] 2023-09-26 02:31
If you prefer stronger colors, it sometimes makes sense to switch off gamma correction:
```x3d
<scene is="x3d">
    <environment gammaCorrectionDefault='none'></environment>
    <navigationInfo is="x3d" type='"examine" "any"' explorationMode="all"  id="navType" ></navigationInfo>
 ```
It looks stronger but is considered less accurate (depending on how the texture image is generated).

**Comment by whunter** [comment] 2023-09-27 13:46
Hi @andreasplesch, thanks for getting back to me. I think, if the option is realistic, that we'll just pin our repo to 1.8.2 until your fix is merged. Do you expect that you all will create another release soon or will it be some time? Also, do you plan on leaving 1.8.2 up on this cdn for a while? https://unpkg.com/x3dom@1.8.2/x3dom.js That's where we're pulling it from.

If you don't mind, could I pick your brain for one second? Are the models we're producing overkill? You asked about the hi-res versions. They're pretty big.
```
HighRes_VTEC000004914_X3D.png 35.6 MB
HighRes_VTEC000004914_X3D.x3d 107.8 MB
```
I think these versions are mostly for preservation purposes though (we're a library). 

But even the low res versions we've produced, which were intended for the web, are detailed enough to break the browser apparently. Like I said, I don't really know much about the 3d domain. I just don't want us to put ourselves in a position where we've produced all this content and we can't find a tool that can render it.

Should we dial it down a little on our models? Any feedback would be greatly appreciated, even if it's just "yeah, that stuff's too big"

Thanks for your time.

**Comment by andreasplesch** [comment] 2023-09-28 03:06
@tsturm is managing releases but I think it will be some time before we will release the next version. unpkg.com derives from npm and there are no plans to remove anything from there.

x3d is also considered an archival format because it so well defined. It is also used for 3d printing where details cannot be simulated by gfx effects. So nothing wrong with large models there. In fact, it might be an idea to offer the hires models for download in particular for 3d printing purposes.

The culprit is the Math.max() function where we just did not anticipate larger models. So it was really just an oversight. There is a way to patch the function which is involved after getting x3dom from unpkg as well.

For the web the LowRes models are probably still considered large, mostly due to file size and processing requirements, not so much due to the number of triangles and points since GPUs can now deal with those. A standard trick for more efficient rendering is to minimize the number of triangles and show interesting surface detail by using a normal texture map at the same resolution as the color texture map. The normal map will be used for lighting fine details although the actual surface is much smoother. But the option of generating a normal texture map may not be available with Agisoft Metashape software. If it is, take a look at https://doc.x3dom.org/tutorials/lighting/commonSurfaceShaderNode/example.html.

You probably want to see that the models still render well on a budget phone. A simple additional test is pressing 'm' which will switch to points rendering. In the case of the butterfly the density of points is sufficient to almost fill in the complete butterfly at reasonable zoom levels. To me that suggests that perhaps half the number of points would still do a good enough job but the library priorities would emphasize high fidelity, of course. This is really a subjective decision which depends on competing interests. It might be necessary to involve domain experts to get a sense of the degree of loss of detail which may be acceptable.

**Comment by whunter** [comment] 2023-09-28 15:19
Thanks for the feedback. I really appreciate it. You're correct, the higher-res versions are a high priority and we are planning on offering them for download.

I guess I really just have one concern with the size of our "low-res" models and it could be completely unfounded because I don't know enough about what's going on "under the hood." And I'd like to get the opinion of @npolys on this as well. 

You said that 1.8.3 is "attempting to fill in missing indices." Does this mean that you're making an attempt to approximate the location of coordinate points that are lost due to the js engine limitations? If so, that makes sense but it made me curious about the implementation. Imagine a scenario where I'm trying to render a model with 2x the number of indices that can be handled by the js engine, so 130k points? Would x3dom render the first half of the input and then try to approximate the second half? Or is the "error" somehow spread out evenly throughout the model?

Just based on my wild guesses as to how this stuff works, it seems like the more points that are lost due to browser limitations the more of a chance for "weird stuff" to happen in rendering. To me it seems like we would ideally want our models to approach this limit without going over, basically because when I enter input I want to be able to predict the output and if an algorithm is approximating lost input that seems to increase the possibility for error. 

Is my understanding of what is happening even remotely close to reality? Am I correct in my thinking that if we avoid going over the browser limitations that our models will be less prone to rendering errors? Or does x3dom handle this problem in a way that's more graceful/effective than I'm imagining?

Again, thanks for your time.

**Comment by andreasplesch** [comment] 2023-09-28 16:08
I was really referring to something else. It is about texture coordinates not actual points.

This was an attempt to avoid crashes for models which have not enough texture coordinate points. These models actually are not X3D spec. compliant but do occur. Each vertex (point) also needs a texture coordinate so in order to render something /not crash) we now assign (an almost arbitrary) texture coordinate if the file itself does not have enough texture coordinates to map to each point.

But this involves finding the maximum index into texture coordinate array requested in order to check if we need to do this, and this additional checking now hits the Math.max() limits.

x3dom in general is not trying to do any magic guessing, and just renders what it is given. It does do a fair bit of validation but mostly avoids catching errors for performance reasons. So it can fail.

The specific limit here is the number of values in the texCoordIndex attribute. In the example, the attribute has 599976 values but Math.max() can only take 65536 values as this is general limitation of functions in common javascript engines.  So it seems unlikely that you could simplify the model by that much.

The fix replaces Math.max with a more robust method which is only limited by memory.

Consider hosting x3dom.js locally rather than using unpkg. It is small relative to the content/models, and you gain full control.

**Comment by whunter** [comment] 2023-09-28 17:36
Thanks @andreasplesch you've been extremely helpful. I think I probably got about half of that, but luckily I'm pretty sure the answer to my question/concern was in that half. Appreciate it.

**Comment by andreasplesch** [comment] 2023-09-28 17:42
Ok, let me close here but feel free to reopen anytime.

**Closed by andreasplesch** 2023-09-28 17:42 UTC

**Comment by andreasplesch** [comment] 2023-09-29 03:47
https://andreasplesch.github.io/Library/Viewer/index.html?url=https://raw.githubusercontent.com/andreasplesch/Library/gh-pages/Models/Animals/VTEC_butterfly/Low3Res_VTEC000004901_X3D.x3d

has the model with the number of points reduced to about 25% (2.3MB). I think it still looks almost indistinguishable from the much larger LowRes model (11MB), even without using a detailed normal texture map. The simplification was done with MeshLab (a good free, scriptable meshing software) and its Quadric Edge Collapse Decimation (with texture) function but likely Metashape could do that as well. With the reduced resolution it is important to use `creaseAngle='3.14'` with the `IndexedFaceSet` which smooths the surface a bit.

**Comment by whunter** [comment] 2023-09-29 13:58
That's really impressive. I honestly can't see a difference. Would you mind if I passed on that .x3d file and your notes here on how it was minimized to our 3D lab?

**Comment by andreasplesch** [comment] 2023-09-30 02:19
Not at all. Please pass on the .x3d file along with anything which may be useful.
