### ISSUE TITLE
X3DOM not working on Chrome latest version - 54.0.2840.xx

### ISSUE THREAD

**Issue by bogdanelloo** [x3dom/x3dom#676] opened 2016-11-05 12:44 UTC
When trying to run X3DOM on chrome 54.0.2840.71 (64-bit) there is nothing rendered and in the browser's console lots of WebGL related WARN messages are being displayed.

I have run multiple tests on multiple machines and operating systems, but was unable to clearly define a recurrence.
Below I will list some of the configurations I have tested:

1. T430, 3632QM i7 Ivy CPU, integrated graphics HD4000, Ubuntu 14.04 - **working**
2. T420, i5 Sandy CPU, integrated graphics HD3000, Ubuntu 14.04,  xfce4 window manage - **NOT working**
3. T430, 3320M i5 Ivy CPU, integrated graphics HD4000, Ubuntu 14.04, xfce4 window manager - **NOT working**
4. T430, 3210M i5 Ivy CPU, integrated graphics HD4000, Ubuntu 14.04, xfce4 window manager - **working**
5. Tested on several Windows machines: T430, T420, Desktop PC and they **work** as expected; except a Windows 10 machine on which it is **not working** (will come back later with details on this machine).

- I have also suspected that the window manager could be the problem, but it seems that it is not because for machines with the same Window Manager (i.e. xfwm4) there were diff. behaviors.

- VGA driver (ubuntu): for the same the same **vga driver=i915** we have experienced diff. behaviors.

- Ran _glxinfo | grep OpenGL_ on multiple linux machines (working and non working) and the results did not provide me with any recurrences what so ever (although I might have been a little superficial in my investigations here).

- The testes have been exec. on several x3dom versions: 1.7.0, 1.7.2-dev-v20

**Comment by tsturm** [comment] 2016-11-05 13:19
Hi,

the current dev works fine on my system(Win10, Chrome 54.0.2840.87 64bit).

Maybe you have enabled WebGL2 support under chrome://flags

There was a problem with x3dom and enabled WebGL2 in Chrome which I've fixed with commit 87f941e14240d665d2deb888059cb0dbdc8c1f04 in the current dev version.

Best Regards,

Timo

**Comment by bauerj** [comment] 2016-11-07 09:30
Hello,

I've got the same problem (Windows 10, Chrome 54.0.2840.87 m)

WebGL2 is disabled.

The only thing in the log on the [test page](http://www.x3dom.org/check/details/) is this:

    Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
    x3dom.js:875 HEAD http://www.x3dom.org/check/details/x3dom.swf 404 (Not Found)

It seems like it is trying to fall back to Flash which doesn't work either.

This is the information I get:
![x3dom info](https://cloud.githubusercontent.com/assets/598790/20052641/2e779cd8-a4d5-11e6-8d2c-677024735def.PNG)

**Comment by bogdanelloo** [comment] 2016-11-07 09:35
Hi Timo,

I have also checked the **WebGL2** experimental flag and it s **DISABLED**.
I will go ahead and update to the last x3dom dev version.
Will let you know...

Cheers,
Bogdan.

**Comment by bogdanelloo** [comment] 2016-11-07 10:24
Below is the complete warning/error stack:

[.Offscreen-For-WebGL-0x15179a18e800]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
[.Offscreen-For-WebGL-0x15179a18e800]GL ERROR :GL_INVALID_ENUM : glTexImage2D: format was GL_DEPTH_STENCIL_OES
[.Offscreen-For-WebGL-0x15179a18cc00]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
[.Offscreen-For-WebGL-0x15179a18cc00]GL ERROR :GL_INVALID_ENUM : glTexImage2D: format was GL_DEPTH_STENCIL_OES
[.Offscreen-For-WebGL-0x15179a18d300]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
[.Offscreen-For-WebGL-0x15179a18d300]GL ERROR :GL_INVALID_ENUM : glTexImage2D: format was GL_DEPTH_STENCIL_OES
[.Offscreen-For-WebGL-0x15179a18da00]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
[.Offscreen-For-WebGL-0x15179a18da00]GL ERROR :GL_INVALID_ENUM : glTexImage2D: format was GL_DEPTH_STENCIL_OES
[.Offscreen-For-WebGL-0x15179a18e800]GL ERROR :GL_INVALID_VALUE : glTexImage2D: 
[.Offscreen-For-WebGL-0x15179a18e800]GL ERROR :GL_INVALID_OPERATION : glDrawElements: No element array buffer bound 3
[.Offscreen-For-WebGL-0x15179a18e800]RENDER WARNING: texture bound to texture unit 3 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
[.Offscreen-For-WebGL-0x15179a18e800]GL ERROR :GL_INVALID_VALUE : glTexImage2D: 171
[.Offscreen-For-WebGL-0x15179a18e800]RENDER WARNING: texture bound to texture unit 3 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

**Comment by bogdanelloo** [comment] 2016-11-07 10:27
The above error stack was created by a machine having the following configuration:
ThinkPad T420, i5 Sandy CPU, integrated graphics HD3000, Ubuntu 14.04, xfce4 window manage

**OpenGL** specifications:

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.1 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 1.40
OpenGL core profile context flags: (none)
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:

**Comment by tsturm** [comment] 2016-11-07 10:33
Does it happen only with a specific example or with all x3dom examples?

**Comment by bauerj** [comment] 2016-11-07 10:35
For me it happens with all examples I've tested.

**Comment by tsturm** [comment] 2016-11-07 10:36
And only on the latest Chrome?

**Comment by bauerj** [comment] 2016-11-07 10:37
It worked before the update but I didn't try downgrading Chrome.

**Comment by bogdanelloo** [comment] 2016-11-07 10:39
For me it is happening only on Chrome 54 and only on some systems, not all of them (see the initial comment).
regarding geometries: I've only tested on one, but I will test some more and give you feedback...

**Comment by tsturm** [comment] 2016-11-07 10:43
Can you also go to [webglreport.com](http://webglreport.com) and look what happens?

**Comment by bogdanelloo** [comment] 2016-11-07 10:49
![webglsupport](https://cloud.githubusercontent.com/assets/17315915/20055165/23acf6e4-a4e0-11e6-9087-bdb85472b939.png)

**Comment by tsturm** [comment] 2016-11-07 10:55
Are there any warnings in the console when you visiting [webglreport.com](http://webglreport.com)?

**Comment by bogdanelloo** [comment] 2016-11-07 11:40
Stack trace below:

[.Offscreen-For-WebGL-0x151799cbc100]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
[.Offscreen-For-WebGL-0x15179a963300]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
[.Offscreen-For-WebGL-0x151799cbc100]GL ERROR :GL_INVALID_ENUM : glTexImage2D: format was GL_DEPTH_STENCIL_OES
[.Offscreen-For-WebGL-0x151799cbba00]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
[.Offscreen-For-WebGL-0x151799cbba00]GL ERROR :GL_INVALID_ENUM : glTexImage2D: format was GL_DEPTH_STENCIL_OES

**Comment by tsturm** [comment] 2016-11-07 12:27
Okay, that looks quite similar to your x3dom stack trace. Seems the latest Chrome have a general problem with some hardware configurations.

**Comment by bitlejac** [comment] 2016-11-07 14:47
Will you guys (x3dom) provide a hot fix for this? And if yes, how soon?

**Comment by tsturm** [comment] 2016-11-07 15:09
The problem is that I can't reproduce the problem on any of my systems.

**Comment by andreasplesch** [comment] 2016-11-07 15:11
Just as another data point, for me on Chrome
Version 54.0.2840.71 (64-bit)
with nvidia driver v. 361.28 on Xorg X server 1.18.4 on 64 bit linux everything works fine.

**Comment by bogdanelloo** [comment] 2016-11-07 15:18
Hi Andreas,

What CPU do you have?
What if you disable the dedicated VGA card (Nvidia) and try with the integrated one (that is if your CPU provides this)?

PS: the reason I have also listed the CPU type and VG

**Comment by tsturm** [comment] 2016-11-07 15:19
Can someone of you try if the problem also occurs on the latest [Chrome Canary](https://www.google.de/chrome/browser/canary.html)?

Can you try other WebGL content on the affected systems (e.g [ThreeJS](https://threejs.org/examples/))?

**Comment by bogdanelloo** [comment] 2016-11-07 15:23
ThreeJS is working.

**Comment by bogdanelloo** [comment] 2016-11-07 15:24
Chrome Canary is currently not available on the linux platform.

**Comment by tsturm** [comment] 2016-11-07 15:27
[Chrome Dev](https://www.google.com/chrome/browser/desktop/index.html?platform=linux&extra=devchannel) or [Chrome Beta](https://www.google.com/chrome/browser/beta.html?platform=linux)?

**Comment by bogdanelloo** [comment] 2016-11-07 15:30
@tsturm - if you still cannot reproduce the problem I can do a screen share. Just say the word.

**Comment by bitlejac** [comment] 2016-11-07 15:32
this is my current version.

Google Chrome54.0.2840.90 (Official Build) (64-bit)
OS	Linux 
JavaScript	V8 5.4.500.40
Flash	23.0.0.205
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36
Command Line	/usr/bin/google-chrome-stable --wm-user-time-ms=14251552 --flag-switches-begin --flag-switches-end --disable_transparent_visuals --window-depth=24 --x11-visual-id=32


but as @bogdanelloo said, i have integrated video card, and that's the only difference between his and mine machine.
I am experiencing the problem, and he don't.

**Comment by tsturm** [comment] 2016-11-07 15:34
@bogdanelloo - can you send me your example?

timo.sturm(at)igd(dot)fraunhofer(dot)de

**Comment by andreasplesch** [comment] 2016-11-07 15:54
```
localhost ~ # lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
00:16.0 Communication controller: Intel Corporation 7 Series/C210 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 1 (rev c4)
00:1c.3 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 4 (rev c4)
00:1d.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation H77 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 7 Series/C210 Series Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GK104 [GeForce GTX 660 OEM] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK104 HDMI Audio Controller (rev a1)
02:00.0 Network controller: Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 07)
```
```
...
DMI: Dell Inc. XPS 8500  /0NW73C, BIOS A10 10/19/2012
...
smpboot: CPU0: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (fam: 06, model: 3a, stepping: 09)
```
The integrated vga on this DELL desktop is not accessible.

**Comment by bogdanelloo** [comment] 2016-11-07 16:18
@andreasplesch - I tried to catch the issue on several windows based machines, but I was not able to.

**Comment by tsturm** [comment] 2016-11-07 16:30
Is any of this examples working for you:

* Examples without PickingPass

** [X3DOM 1.7.0 without PickingPass](http://examples.x3dom.org/chromeBug/test_170.html)
** [X3DOM 1.7.1 without PickingPass](http://examples.x3dom.org/chromeBug/test_171.html)
** [X3DOM 1.7.2 without PickingPass](http://examples.x3dom.org/chromeBug/test_172.html)

* Examples with PickingPass

** [X3DOM 1.7.0 with PickingPass](http://examples.x3dom.org/chromeBug/test_170_picking.html)
** [X3DOM 1.7.1 with PickingPass](http://examples.x3dom.org/chromeBug/test_171_picking.html)
** [X3DOM 1.7.2 with PickingPass](http://examples.x3dom.org/chromeBug/test_172_picking.html)

**Comment by bogdanelloo** [comment] 2016-11-07 16:36
The all work, but the following warning messages are displayed in the browser's console:

[.Offscreen-For-WebGL-0x151799a40000]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
[.Offscreen-For-WebGL-0x151799a40000]GL ERROR :GL_INVALID_ENUM : glTexImage2D: format was GL_DEPTH_STENCIL_OES

**Comment by tsturm** [comment] 2016-11-07 16:52
That sounds good.

The warnings must come from Chrome internally because there is no single gl.getIntegerv call in x3dom themselve.

Do you get the same warning on any ThreeJS example?

**Comment by bogdanelloo** [comment] 2016-11-07 17:10
On Three.js the stack looks like this:

VM96 three.js:19318 THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.get @ VM96 three.js:19318WebGLRenderer @ VM96 three.js:19725init @ VM101 webgl_animation_cloth.html:271(anonymous function) @ VM101 webgl_animation_cloth.html:120
VM101 webgl_animation_cloth.html:1 [.Offscreen-For-WebGL-0x2247f04f0100]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command

**Comment by tsturm** [comment] 2016-11-07 17:14
okay, there is also a GetIntegerv Error.

Can you enable WebGL 2 under chrome://flags and try it again?

If WebGL2 is enabled I force x3dom to ignore the supported WEBGL_depth_texture extension.

**Comment by bogdanelloo** [comment] 2016-11-07 17:23
Enabled WebGL 2.0 Prototype and here is the ThreeJS stack trace:

VM58 three.js:19318 THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.get @ VM58 three.js:19318WebGLRenderer @ VM58 three.js:19725init @ VM63 webgl_animation_cloth.html:271(anonymous function) @ VM63 webgl_animation_cloth.html:120
VM63 webgl_animation_cloth.html:1 [.Offscreen-For-WebGL-0x1c075cde7100]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
VM63 webgl_animation_cloth.html:1 [.Offscreen-For-WebGL-0x1c075d4ac700]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command

**Comment by tsturm** [comment] 2016-11-07 17:25
Sorry, I mean enable WebGL2 and try X3DOM.

**Comment by tsturm** [comment] 2016-11-07 17:27
Can you type ```console.log(x3dom.caps.DEPTH_TEXTURE);``` in the chrome console and send me the result.

**Comment by bogdanelloo** [comment] 2016-11-07 17:34
DEPTH_TEXTURE: null

**Comment by tsturm** [comment] 2016-11-07 17:34
And your example is still broken?

**Comment by bogdanelloo** [comment] 2016-11-07 17:36
yes!
This must be it as I just checked on one of the working machines and the DEPTH_TEXTURE object is present.

**Comment by bogdanelloo** [comment] 2016-11-07 18:11
For the machine that fails the DEPTH_TEXTURE is null for both configurations: WebGL2 ENABLED and DISABLED, meaning that ctx.getExtension("WEBGL_depth_texture") returns null.

**Comment by tsturm** [comment] 2016-11-08 09:38
I don't think that the missing extension is the main problem. If the WEBGL_depth_texture extension is not supported, x3dom falls back to the native Renderbuffers. If the above examples work, all other examples should also work. I think it must be a problem with your input data or the ```Multipart-Node```. Have you tried to load the model simply as ```Inline-Node```.

**Comment by bogdanelloo** [comment] 2016-11-24 15:31
Tested on version 54.0.2840.100 (Official Build) (64-bit) and was not able to reproduce the issue anymore, so it seems that it was fixed!
I will consider this issue as CLOSED.

**Closed** 2016-11-24 15:31 UTC
