### ISSUE TITLE
Model freezes X3DOM, errors in console

### ISSUE THREAD

**Issue by sevaa** [x3dom/x3dom#515] opened 2015-07-10 02:07 UTC
To reproduce:
 - navigate to http://www.jishop.com/temp/x3d/
 - click on "PDB-1XCT-surf-bychain-display" (the model loads and displays as expected)
 - click on any other model in the nav bar (it doesn't load)
 - or try rotating the model (it doesn't anymore)

In the browser's console window, there are JavaScript errors. The first one goes: "Uncaught TypeError: Cannot read property 'getURL' of null", investigation shows that a shape object has a null _namespace.

Tested on Chrome 43 on Win64. If the X3D in question is somehow malformed (it's tool-generated), please tell how exactly.

**Comment by mlimper** [comment] 2015-07-10 07:41
You can validate your X3D code with existing tools (for example, https://savage.nps.edu/X3dValidator).

But if you write X3D code directly as part of an HTML page, you should make sure that there are no self-closing tags, since this will not work with HTML (only XHTML).

**Comment by sevaa** [comment] 2015-07-10 14:19
My mistake: the model to click is "PDB-1XCT-surf-bychain-display".

It doesn't pass validation because the validator doesn't support BinaryGeometry. X3DOM does, however.

It looks like the shape from the 1XCT model is somehow being rendered after it's been deleted from the scene. The _namespace property is reset to null in that scenario, nowhere else. Specifically, what fails is the binary geometry loading logic.

**Comment by mlimper** [comment] 2015-07-20 12:52
I cannot reproduce this behavior with the above steps. I followed the instructions:
* navigate to http://www.jishop.com/temp/x3d/
* click on "PDB-1XCT-surf-bychain-display" (the model loads and displays as expected)

Everything ok so far - the next two steps were:
* click on any other model in the nav bar (IndexedFaceSets - but others worked too)
* try rotating the model (I did that, worked)

I was also able to switch between models, for multiple times.

But, in fact, the error you described occured as soon as I was trying to switch between the models really fast (faster than I usually would,  I had to give my best to be really fast - but this probably highly depends on the particular connection bandwidth...).

This seems to be a problem with the download and the respective callback code of the inline or binary geometry nodes, being invoked after the inline node (or its URL?) has already been exchanged, order to load the new model.

How do you exchange the model? Are you exchanging the URL, or the inline node itself? Could you share 1-2 lines of your javascript code?

**Comment by sevaa** [comment] 2015-07-20 17:48
I still can observe the issue. Since the model is not well centered, I usually also click "A" to center the model first, not sure if it matters.

Anyways, the HTML goes:

<x3d xmlns="http://www.x3dom.org/x3dom" id="x3d" showlog="false" showstat="false" x="0px" y="0px" width="1000" height="600">
	    <scene>
		    <inline id="inline" render="true" bboxcenter="0,0,0" bboxsize="-1,-1,-1" load="true" namespacename=""></inline>
	    </scene>
    </x3d>

And the Javascript to load a model goes:

	        document.getElementById("inline").url = ModeName + ".x3d";

**Comment by mlimper** [comment] 2015-07-20 18:13
Thanks.
So normally I would guess that the problem is that the binary containers behind the old URL have not been downloaded yet. As soon as their callback gets executed, something goes wrong, since the inline content (including the binary geometry node, for example) has already been replaced.

But you say this occurs also if you load a model, wait until everything is 100% loaded (check the spinning wheel and load counter on the upper left), and then select another model?

**Comment by sevaa** [comment] 2015-07-20 19:16
It's not a loading latency issue - the model only has one mesh, X3DOM won't be able to render it unless the geometry file and vertex colors file are already loaded. And it's rendered, with colors.

Anyway, I load the 1XCT-display model, it shows up off center. I press A to bring it in the center. Then I press another model in the left hand menu. The 1XCT model doesn't disappear, but doesn't react to mouse moves anymore, either. In the browser console there's a bunch of errors starting with the following one:

Uncaught TypeError: Cannot read property 'getURL' of null

Which is on line 21891, and goes:
{var xmlhttp0=new XMLHttpRequest();xmlhttp0.open("GET",shape._nameSpace.getURL(binGeo._vf.index),true);xmlhttp0.responseType="arraybuffer";shape._nameSpace.doc.downloadCount+=1;xmlhttp0.send(null);xmlhttp0.onload=function()

Debugging shows that shape._nameSpace is null, which is consistent with the shape being already removed from the scene. 

Why would X3DOM try to load a binary geometry while the model is in the process of unloading - beats me.

Subsequent errors in the console are: Uncaught TypeError: Cannot read property 'transform' of undefined

**Comment by mlimper** [comment] 2015-07-21 16:16
> Anyway, I load the 1XCT-display model, it shows up off center. I press A to bring it in the center. 

Just as a remark, in case you are interested in that:
You can also trigger the "A" programmatically after download using the "onload" callback of the inline, for example. Manipulating the transition time, you can also do this without animation.
Another possibility is to center the model during offline conversion by creating a corresponding viewpoint node (in aopt, this can be achieved using -V, for instance).

> Why would X3DOM try to load a binary geometry while the model is in the process of unloading - beats me.

Yes, this is really strange - can you try if the same occurs if the model is _not_ visible? I know this sounds weird, but the background is that X3DOM is always triggering downloads when a model is visible for the first time. Therefore, one explanation could also be the following:
* X3DOM removes the deleted content
* For some reason, the shape still exists in the renderer for another frame
* During that frame, X3DOM triggers a download... but the shape is already partially deleted (namespace is null) -> the bug occurs

**Comment by sevaa** [comment] 2015-07-21 16:47
Tried without centering - same thing. The 1XCT-display model loads, a corner of the mesh is visible even without centering, a bit of blue and yellow in the lower left corner. I then click on "Primitives" (the topmost in the nav bar) - the blue and yellow mesh does not go away, can't be rotated by mouse anymore.

Let's start with you reproducing the condition. What browser are you doing this on? I can reproduce this on Chrome and Firefox (on Win7-64), MSIE 11 on Win8.1-64.

**Comment by mlimper** [comment] 2015-07-21 18:59
I am on Ubuntu Linux 14.04 with Chrome or Firefox, but I think that does not matter - I was just able to reproduce the issue - reliably, it seems:

Case 1 - to reproduce the bug:
* Click on PDB-1XCT-surf-bychain-display, let it finish loading. A corner of the model will be visible.
* Click on "IndexedFaceSets" - the bug occurs.
* Reproducing the bug only works if the cache has been cleared before (at least on my machine - applies to both browsers I used)

Case 2 - to "workaround" the bug:
* Click on PDB-1XCT-surf-bychain-display, let it finish loading. A corner of the model will be visible.
* Move the model out of the view frustum (by dragging with middle mouse button) - make sure it is a bit away from the frustum, so that its bounding box (which is used for visibility computation) is definitely invisible
* Click on "IndexedFaceSets" - it works. You can center the model by pressing "A", no errors.

It first felt a bit random that the bug in Case 1 only occured "sometimes" with my system, but I think this was due the fact that I did not always clear the cache before loading again. Do you have your cache disabled, or do you always clear it (just interested)?

So, for the Case 2, I suppose you can also reproduce this behavior, i.e., create a situation where the bug does _not_ occur by moving the model outside the frustum?
I can realibly reproduce both Cases, 1 and 2, on Chrome as well as on Firefox.

Seems we have to look into the code then.

**Comment by sevaa** [comment] 2015-07-21 19:09
I could reproduce Case 2 after some trying. It only proves that the re-render logic is not triggered when the model is off screen; that makes sense. Naturally, this is not a workaround that we would offer to site visitors to follow.

The caching could be relevant; if the binary geometry loading logic is skipped because of caching, the error code path is not followed. Maybe caching strategies are different in Chrome on Windows and on Ubuntu; on my machine, Case 1 reproduces every time, even without explicit cache clearing.

What code would you like to see? My code consists of one line of Javascript that I've already shared. The rest is X3DOM code. I'm loading X3DOM via the following lines:

&lt;script type=&#39;text/javascript&#39; src=&#39;http://www.x3dom.org/download/dev/x3dom-full.js&#39;&gt; &lt;/script&gt;
&lt;link rel=&#39;stylesheet&#39; type=&#39;text/css&#39; href=&#39;http://www.x3dom.org/download/dev/x3dom.css&#39;&gt;&lt;/link&gt;

**Comment by mlimper** [comment] 2015-07-21 19:33
Actually I meant let's look into the X3DOM code ;-)
It's an open source project, so maybe we can fix this together:

Here's the code that is executed when a node is removed from the DOM:
https://github.com/x3dom/x3dom/blob/master/src/X3DDocument.js#L108

Here's the start of the rendering loop:
https://github.com/x3dom/x3dom/blob/master/src/gfx_webgl.js#L3213

Then, there is a step that collects all "Drawable Objects":
https://github.com/x3dom/x3dom/blob/master/src/gfx_webgl.js#L3553

This step involves getting the drawable objects corresponding to a shape node:
https://github.com/x3dom/x3dom/blob/16dc05fa5d180fb25f8887a3d96126a52ec952f4/src/nodes/Shape/X3DShapeNode.js#L99

Finally, all non-culled drawable objects are rendered:
https://github.com/x3dom/x3dom/blob/master/src/gfx_webgl.js#L3658


One could try to set some debug flag (entitled "wasRemovedFromDOM" or so) on a shape when it is being removed from the DOM, for example in this line:
https://github.com/x3dom/x3dom/blob/master/src/X3DDocument.js#L122
As you can see, there is already a comment "// TODO: more cleanups, e.g. texture/shader cache?", so maybe we are on the right way.

One could then check the value of this debug flag when the shape is being collected by the renderer
and do a console.log, or alert, or whatever, in case it has already been set:
https://github.com/x3dom/x3dom/blob/16dc05fa5d180fb25f8887a3d96126a52ec952f4/src/nodes/Shape/X3DShapeNode.js#L99

This way, one could verify that the shape is being collected by the renderer after being deleted from the DOM.

**Comment by sevaa** [comment] 2015-07-21 19:47
Please clarify the intended meaning of "one". More specifically, you or me?

**Comment by tsturm** [comment] 2015-07-21 20:50
Problem should be fixed with my last commit.

Can you try it again with the latest dev-version?

**Comment by sevaa** [comment] 2015-07-21 20:54
Doesn't reproduce. Thank you!

**Comment by mlimper** [comment] 2015-07-21 23:55
Thanks timo!

**Closed by mlimper** 2015-07-21 23:55 UTC
