### ISSUE TITLE
glTF model CesiumMilkTruck wheels does not display properly

### ISSUE THREAD

**Issue by cx20** [x3dom/x3dom#709] opened 2017-01-11 15:57 UTC
I tried to display the glTF sample using X3DOM 1.7.3-dev. However, the wheels were not displayed correctly.
https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF-Binary
![image](https://cloud.githubusercontent.com/assets/1833979/21854857/ae469dac-d85f-11e6-8605-df2510e74b1f.png)

I confirmed that it can be displayed by individually settings the mesh of the car body and the wheel like the sample below. However, I think that this model should be displayed without specifying individual settings.

https://examples.x3dom.org/gltf/

**Comment by skluge** [comment] 2017-01-16 13:34
The x3dom glTF-Loader is only supposed to load mesh and materials.
So the node and transformation tree from the glTF is not used.

**Comment by cx20** [comment] 2017-01-16 15:25
I understood that the glTF Loader in x3dom does not use nodes and transformation trees yet.

Is it the same reason why Buggy.gltf are not displayed correctly?
https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=sampleModels&model=Buggy&scale=0.02&type=glTF-Binary
![image](https://cloud.githubusercontent.com/assets/1833979/21988466/ac16a66e-dc4a-11e6-8769-f6389d89c8bd.png)

I expect to be displayed as follows.
![image](https://cloud.githubusercontent.com/assets/1833979/21988492/bdfa80bc-dc4a-11e6-9bb3-7e3a00c34180.png)

**Comment by skluge** [comment] 2017-01-17 15:13
Yes, the problem is, that the meshes are initially positioned in the world center and then transformed to the correct position.
As for the milk truck example, the mesh of the wheels is positioned at the origin, and in the node-tree it is referenced two times at different positions. But since the node tree is not loaded, the mesh stays at the origin.

**Comment by andreasplesch** [comment] 2017-01-18 18:15
Would the idea of an ExternalGroup help, in addition to ExternalShape, and ExternalGeometry ? Presumably, as a grouping node ExternalGroup could contain a node tree with the Transforms ?

**Comment by mlimper** [comment] 2017-01-18 18:21
There was already a proposal of making Inline nodes support gltf - could that be a solution?

**Comment by andreasplesch** [comment] 2017-01-18 18:29
Yes, I think gltf Inlines would be a good solution. Perhaps with namespaced names for the nodes/shapes/geometries so they are available from the main scene ?

**Comment by andreasplesch** [comment] 2017-02-19 04:45
Before going to full Inline glTF scene support, it may be possible to just support the glTF transforms as a graph.localMatrix for each shape.

Graph.localMatrix seems to fit this kind of purpose but may not be used at all in the rendering ?

It sounds like an extra transform at the shape level ?

https://github.com/x3dom/x3dom/blob/master/src/util/DrawableCollection.js#L137

Defines a drawable.localTransform from localmatrix but localtransform is then seemingly never used.

For simplicity, I would just apply the localtransform to the drawable.transform in addshape.

Then the glTF loader could assign the computed world transform of a mesh to graph.localMatrix of the shape.

Before I give this a try, would this work with multiple meshes in a scene ?

Another option may be to internally wrap transform nodes around each glTF node when loading. This would be closer to the glTF structure and then externalGroup may be a better fit.

**Comment by andreasplesch** [comment] 2017-02-19 14:39
It looks like there is only one drawable per glTF scene and therefore only one localmatrix. So this idea would not work for multiple meshes with transforms.

So the cleanest would still be an external group node which generates a transform per glTF node which then can contain one shape per glTF mesh if there is one.

This means a new loader, and somehow sharing the buffer between shapes.

Another approach may be to populate the semantics and then see how they get used in gfx_webgl and shaders.

**Comment by andreasplesch** [comment] 2017-02-20 18:43
Just documenting uniform matrix flow as observed to understand how the glTF vertex shader gets its input:

gfx_webgl.renderShape : uses transform from drawable (from graph) to calculate shader parameters (uniforms); one per shape (reflects x3d hierarchy etc.).
gfx_webgl.renderShape //render from glb data section : goes through all meshes in a single shape. meshes have their own gltf material which could hold glTF transforms from nodes.
gfx_webgl.renderShape : calls mesh.material.bind per mesh with updated shape transforms/uniforms
glTF.glTFMaterial.bind: calls material.updateTransforms to update the glTF shader parameters with the shape transform/uniforms
glTF.glTFMaterial.updateTransforms: the provided shape transforms/uniforms are assigned to the mapped gfTF shader program uniforms.
custom vertex shader then actually draws using the uniforms.

It should be possible to multiply in the glTF provided, computed global model per mesh transforms in updateTransforms. Not sure where to store best this computed, global, per mesh transform during loading ? material.technique.parameters.transformparameter.value ?

This may work and I may give it a try.

glTF parameter animations (and skinning) may need a new design altogether ?

**Comment by andreasplesch** [comment] 2017-02-24 16:16
Following the idea above, I modified the x3dom gltf loader to properly use the node transforms:

https://andreasplesch.github.io/gltf-test/examples/x3dom/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF-Binary

For ease of use, the modifications currently reside in a separate (user script) file:

https://gist.github.com/andreasplesch/41f29833c4bbe2e638b3acae0d49f160

which I now use with my fork of @cx20 's gltf-test pages . With it, all the examples with node trees work (https://andreasplesch.github.io/gltf-test/) .

If there is interest ( @skluge, @mlimper ? ) , I can submit a PR for the gltf loader for a intermediate solution until there is a full solution for a gltf Inline scene with the node hierarchy represented as a transform hierarchy, and each mesh (or primitive?) as a separate Shape.

I will also offer a PR to cx20 gflt-test repo .

**Comment by mlimper** [comment] 2017-02-24 18:15
Thanks! Great to hear that the mentioned glTF test models work with transforms now.

I don' have time to look into this, but maybe someone else could check.

**Comment by andreasplesch** [comment] 2017-02-24 20:36
It sounds like it may be useful to prepare a PR for easy diff viewing ? I may be so bold to include @tsturm here.

The current gltf x3dom at example https://examples.x3dom.org/gltf/ is not affected since it only uses the gltf meshes (without the transforms) directly with the #mesh url suffixes.

The underlying principle for externalShape to represent a whole gltf scene including its transform tree that in many cases the node tree is there for instancing only and the transforms do not need to be accessible/mutable from the outer scene graph.

My glTF loader patch just constructs a worldTransform for each node while traversing. It is then available for each primitive in each mesh and used when updateTransforms is called for each frame. In updateTransforms the worldTransform is factored into each of the available shader uniforms.

Still missing is to update the picking renderer to also call updateTransforms and to properly treat some of the more exotic uniforms.

Also it would be good to have a getVolume() function for externalShape (similar to externalGeometry).

For animations I think it may be necessary to construct an actual x3d transform hierarchy (for which I have some vague ideas). I probably would first introduce a new externalGroup grouping node with a URL field and internal MFNode field . For parsing the existing glTFloader functions can be probably used. So it may be quite feasible. After this works externalGroup could be integrated into Inline.

Skinning support would probably first require checking how it compares with HAnim.

**Comment by andreasplesch** [comment] 2017-02-25 00:30
Ok, I submitted a #723 for consideration.

**Comment by cx20** [comment] 2017-02-25 01:21
@andreasplesch Many Thanks!

I confirmed that the wheels of CesiumMilkTruck are correctly displayed.

![image](https://cloud.githubusercontent.com/assets/1833979/23326583/51f96510-fb42-11e6-893c-e58803131845.png)

This issue can be closed by the issue.

BTW, I hope that models not in the binary form of glTF will be displayed.

**Comment by andreasplesch** [comment] 2017-02-25 04:23
It would be nice if the other glTF flavors could also be loaded. This should be relatively straightforward to add if there is a demand.

I do think the single file binary glTF is the most attractive flavor and AFAIK will move into the core spec.

Feel free to modify the replacement shape for non binary glTFs in your glTF-test repo.

**Comment by andreasplesch** [comment] 2017-03-10 16:20
@cx20 : I think you could close this issue yourself.

**Closed** 2017-03-10 16:38 UTC
