### ISSUE TITLE
Mouse wheel zoom behaviour is opposite to some other players

### ISSUE THREAD

**Issue by gwgill** [x3dom/x3dom#486] opened 2015-04-01 03:54 UTC
In "examine" mode, scrolling the mouse wheel up, zooms out. This is exactly opposite to the convention used by almost all other applications. Web browsers for instance, zoom in (enlarge) with <ctrl> wheel scroll up.

**Comment by Goutte** [comment] 2015-06-22 16:54
:+1: 

Usually this is because the developers use iOS.

**Comment by Goutte** [comment] 2015-06-22 20:21
The related code [is here](https://github.com/x3dom/x3dom/blob/master/src/X3DCanvas.js#L331) if you want to fork your own version.

**Comment by mlimper** [comment] 2015-06-23 08:52
Maybe this is a bit different from 2D web pages:
More than with a 2D page, the 3D viewer is based on the notion of interacting with a real _object_. And the intuition behind the interaction is then that your are pushing or pulling the object (or the scene) with your mouse wheel. If you think about it like that, it is pretty intuitive, at least in my opinion.

I will not call the method you would probably favor "Translate Viewer" method, and the other one "Translate Scene" method.

I have made a quick look around a saw the following:

"Translate Viewer" used in
* InstantReality Player
* MeshLab

"Translate Scene" used in
* Three.js (at least in this example here: https://www.heroforge.com/)
* Potree

It looks like we would not be able to satisfy if we implement only one of the behaviors (especially not if we now change the default behavior X3DOM users might have been got used to).

So, what about introducing an option for this?
Should be part of the NavigationInfo node.

**Comment by Goutte** [comment] 2015-06-23 11:58
I've always thought of the mouse wheel as controlling the Camera itself, not the scene. I suppose it's a habit one grows into, and then the preference falls into the "consistency" cognitive bias.

An option is the way to go, then ! :+1:

I'll try my hand at it later this month, if it's not already done by someone else by then.

**Comment by mlimper** [comment] 2015-06-24 08:28
another one, from autodesk, that has the "translate scene" method:
http://lmv.rocks/
So we really should support both.

Thanks in advance for working on this!

**Comment by Goutte** [comment] 2015-06-24 08:46
What would be a good name for the option, in your opinion ? Something like `invertScroll` ?

**Comment by mlimper** [comment] 2015-06-24 09:08
Is this limited to the mouse wheel?
Or is it affecting also the right-click behavior?

* invertScrollDirection
* invertZoomDirection
* invertWheelDirection

**Comment by Goutte** [comment] 2015-06-24 09:23
I like the right-click behavior as it is (up to zoom in the camera, down to zoom out). I think we should make an option for scrolling only, and if anyone wants to change the right-click behavior, it belongs in another option.

Maybe also add the fact that it is `vertical` scrolling that is affected, like `invertVerticalScrollDirection`.

I also prefer `scroll` to `wheel`, both for consistency with DOM events and because there's scrolling on a touchpad with no actual wheel. This is debatable, of course.

**Comment by Goutte** [comment] 2015-06-24 10:12
Also, seems like `wheel` is [the new standard](https://developer.mozilla.org/en-US/docs/Web/Events/wheel). Grmbl. What are they thinking ?

**Comment by Goutte** [comment] 2015-06-25 13:38
Regarding the documentation, I can only find `doc/x3doc/base/author/configuration.html` to edit. Do you write documentation directly in HTML or is this a generated file ?

**Comment by Goutte** [comment] 2015-06-25 13:52
Looks like the file is written into _by hand_. Unusual, for documentation, but I've edited it, and took the liberty of removing some bloating `style` attributes along the way.

**Comment by mlimper** [comment] 2015-06-25 13:56
no, documentation is mostly written by a nightly process, using jsdoc

just format the comments for your node / field accordingly (see the existing nodes for examples)

**Comment by mlimper** [comment] 2015-06-25 13:57
(so, you would probably want to add a field to the navigationinfo node, instead of manipulating the configuration.html)

**Comment by Goutte** [comment] 2015-06-25 13:59
But... But...

There are inconsistencies in the file !? Some `td` are closed, some are not !?

I figured that it must have been the work of a human !
Ok, I'll dig deeper. I already heavily documented the parameter in the code, I'll play with the documentation generator to see if it digests it.

**Comment by sressler** [comment] 2015-06-25 14:33
I'd suggest "reverse" rather then "invert"...invert is like inside out.
So reverseScrollDirection etc...Sandy

On Wed, Jun 24, 2015 at 5:08 AM, Max Limper <notifications@github.com>
wrote:

> Is this limited to the mouse wheel?
> Or is it affecting also the right-click behavior?
>
>    - invertScrollDirection
>    - invertZoomDirection
>    - invertWheelDirection
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x3dom/x3dom/issues/486#issuecomment-114796116>.
>



-- 

Sandy Ressler

http://www.sandyressler.com @sressler

http://www.bitcoininplainenglish.com  @btcplainenglish

sressler at acm.org

**Comment by Goutte** [comment] 2015-06-25 14:40
:+1: for `reverse`.

`python manage.py --rebuild --docs all` yells at me. I suppose it is not that important if a nightly builds it anyway.

I'll wait some more to give time to other people to voice their opinions before submitting a

**Comment by Goutte** [comment] 2015-06-25 14:43
And I did not touch at the already [existing `NavigationInfo` usage](https://github.com/x3dom/x3dom/blob/master/src/X3DCanvas.js#L471), because of the `doc` passed as parameter. If you say it's safe, I can refactor it to use the same `NavigationInfo` as the wheel events do.

**Comment by mlimper** [comment] 2015-06-26 09:47
the python build script is for the old doc system, there is a new script for the windows machine used for nightly doc build here:
https://github.com/x3dom/x3dom/tree/master/doc

This can also be run locally

**Comment by Hornwitser** [comment] 2016-04-13 11:57
This issue is a duplicate of #454

**Comment by mlimper** [comment] 2016-04-13 12:17
> If you say it's safe, I can refactor it to use the same NavigationInfo as the wheel events do.

Sounds good! @Goutte Do you think you could submit a PR?

**Comment by Goutte** [comment] 2016-04-13 12:29
Nope ! I can't find the code, as my work computer crashed and burned last year, and it's not in my x3dom github fork, oddly enough.

**Comment by t-oster** [comment] 2017-10-04 11:49
Any news on this one?

**Comment by andreasplesch** [comment] 2017-10-04 13:46
https://sourceforge.net/p/x3dom/mailman/message/35929227/ has a discussion and a simple workaround:

'I revised X3DCanvas.js here by just flipping the sign of the increment for the amount of 'drag' at the mousewheel event (-= to +=):'

https://rawgit.com/andreasplesch/d38e877f1a5adfaf36faf4f8769eb8b3/raw/2e4c028bbcfb690e364981b0864dda4abfe57def/x3dom_reverseMousewheel.user.js
```

**Comment by andreasplesch** [comment] 2017-10-29 23:56
before we merge @frattay 's PR, let's take a moment to decide on field name:

1. naturalScroll
2. invertScrollDirection
3. reverseScrollDirection
4. reverseScroll
x. others

I vote for 4.

**Comment by Goutte** [comment] 2017-10-30 11:05
4. is fine by me as well.

**Closed** 2017-11-13 14:22 UTC

**Comment by FrankBuchholz** [comment] 2020-06-12 18:01
Instead of using the new option `<NavigationInfo reverseScroll="true" ... ` you can set the speed to a negative value like this:  `x3d.runtime.speed(-4);`
